# Server properties
server:
  servlet:
    context-path: /tour-api
  port: 8181 #el puerto 8080 esta ocupado

spring:
  # Dev is active by default. This value can be overwritten by java arg param
  profiles:
    active: dev
  application:
    name: api-hero